### ISSUE TITLE
Ability to open Github repos

### ISSUE THREAD

**Issue by cloudrex** [pairhub/pairhub#26]
A link button should be available (preferably alongside the project tag) that opens a new tab to such Github repository.

(Apart from the large hyperlink located at the right once a post is opened)

**Comment by gustavlrsn** [comment]
@cloudrex thanks for you suggestion, I think this is a great idea!

**Comment by treyles** [comment]
I'd like to work on this if nobody else is!

**Comment by gustavlrsn** [comment]
Fixed in #32!
