### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by mittalyashu** [pairhub/pairhub#46]
Add support for markdown in post creation box.

![image](https://user-images.githubusercontent.com/29014463/59146440-9d4f3d00-8a0b-11e9-9e3e-1e5b40cb921d.png)

**Comment by abhishek71994** [comment]
@mittalyashu are you working on this? If not I can work on it.

**Comment by mittalyashu** [comment]
Sure you can work on it @abhishek71994

**Comment by gustavlrsn** [comment]
New iteration of the platform has markdown support! :)
